[package]
authors = ["Omeid Matten <public@omeid.me>"]
name = "warden"
version = "0.1.0"

[dependencies]
erased-serde = "0.1.3"
futures = "0.1.10"
serde = "0.9.9"
serde_derive = "0.9.9"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.4.0"
